### ISSUE TITLE
Disable "leave competition" button once user has participated

### ISSUE THREAD

**Issue by LeBenLeBen** [team-rawbot/rank-me#96]
If you try to leave a competition in which you have participated, you get an error:

```

CannotLeaveCompetitionError
```

We should hide the button if user can’t leave.

**Comment by sephii** [comment]
Actually you can leave a competition you took part in. The exception is raised if you try to leave a competition you have created, because you could then run into the case where no one can remove the competition. The proper way to deal with this would be to force the user to choose another user to take the admin role for the competition if they want to leave, but in the meantime we could just disable the button.

**Comment by LeBenLeBen** [comment]
Oh! Yeah just remove the button when user is the creator then. It rarely makes sense to leave your own competition.
